from colorama import init

init()

text = 'akfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\n\
        akfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\n\
        akfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\n\
        akfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\n\
        akfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\nakfjhaskjdfhaslkjdfhaksjhdfkajsdhfkajsdhfaskjdfh^\n'

print(text)
